// env.ts
export const SUPABASE_URL = "https://cfcfpwsgdkrjqdhbkhlq.supabase.co";
export const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmY2Zwd3NnZGtyanFkaGJraGxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNzgzMjgsImV4cCI6MjA3Mjg1NDMyOH0.lms9iud3JAfRb8lbKRpVKGUykLVgvjmAfXzFt-WIm8I";
